version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: app-postgres-db
    hostname: ${DB_HOST}
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes: 
      - postgres:/var/lib/postgresql/data 
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    env_file:
      - .env
  redis:
    image: redis:7-alpine
    container_name: app-redis-cache
    hostname: ${REDIS_HOST}
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes: 
      - redis:/data  
    env_file:
      - .env
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
  messageboard-app:
    image: messageboard-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
volumes:
  postgres:
  redis:

